### ISSUE TITLE
Sign up fails with unauthorized message (Docker setup)

### ISSUE THREAD

**Issue by un33k** [GraphQL-Portal/graphql-portal#359]
**Describe the bug**
Followed the instruction to start everything via docker, visited the front-end at localhost:8080, attempted to signup, assuming an empty database, signup failed with vague "Unauthorized" message. 

The current status of this repo(s) suggests that the project is not ready yet, however, I just wanted to see if I could minimally create an account and login and look around.  

**To Reproduce**
1. Follow the docker setup instruction
2. Attempt to signup
3. Verify the "unauthorized" error

**Expected behavior**
Minimally, a signup and look around should be possible.  A 204 no content HTTP response is usually for a successful "create" and not for an authorization failure. 

**Screenshots**
<img width="466" alt="Screen Shot 2021-05-24 at 12 25 05 AM" src="https://user-images.githubusercontent.com/407537/119296240-959ff780-bc26-11eb-8211-af5c38fe6477.png">

**Additional context**
A config example that points to a covid endpoint is observed, however, a it is not clear what to add to the example configuration to just login and get a feel for the project.  I am sure adequate documentation will eventually put in place to make the initial experience more smooth.

**Comment by msadovyi** [comment]
Hi, @un33k! You can login using default admin credentials, pass your own as environment variables or use default for testing purposes.
```
"defaultAdmin": {
      "email": "@@DEFAULT_ADMIN_EMAIL",
      "password": "@@DEFAULT_ADMIN_PASSWORD"
 }
 ```
If you want to enable signup you have to pass SendGrid config values and @@PUBLIC_HOST variable, as signup requires confirmation codes:
```
"sendgrid": {
      "senderEmail": "@@SENDGRID_SENDER_EMAIL",
      "confirmationTemplateId": "@@SENDGRID_CONFIRMATION_TEMPLATE",
      "resetPasswordTemplateId": "@@SENDGRID_RESET_PASSWORD_TEMPLATE",
      "apiKey": "@@SENDGRID_API_KEY"
 },
"publicHost": "@@PUBLIC_HOST"
```
You can use the following variables in your SendGrid dynamic template: `confirmationUrl`, `firstName` - confirmation template and `resetPasswordUrl`, `firstName` - reset password template.

Ping me here if you'll still have any issues!

Thanks,
Max.
