### ISSUE TITLE
Cannot run GraphQL Playground

### ISSUE THREAD

**Issue by francislagares** [GraphQL-Portal/graphql-portal#506]
**Describe the bug**
GraphQL Playground throws error.

**To Reproduce**
1. Add OpenAPI as a data source.
2. Create your endpoint and add the data-source.
3. Click View API in Your APIs section.
4. GraphQL Playground opens with following error:
```
{
  "errors": [
    {
      "message": "Query root type must be provided.",
      "name": "GraphQLError",
      "originalError": {},
      "source": {
        "locationOffset": {}
      },
      "stack": [
        "GraphQLError: Query root type must be provided.",
        "    at /usr/local/share/.config/yarn/global/node_modules/graphql-helix/dist/process-request.js:197:49",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
        "    at async Object.processRequest (/usr/local/share/.config/yarn/global/node_modules/graphql-helix/dist/process-request.js:50:20)",
        "    at async /usr/local/share/.config/yarn/global/node_modules/@graphql-portal/gateway/dist/src/server/mesh/graphql-handler.js:55:28"
      ]
    }
  ]
}
```

**Expected behavior**
Create openapi endpoint and make queries with Playground

**Screenshots**
![Playground](https://user-images.githubusercontent.com/43886198/131719297-f552e3d9-2af8-40d2-9ca9-6c1d287348a2.png)

**Comment by msadovyi** [comment]
Hi, @francislagares! Could you provide OpenAPI data source config?

**Comment by msadovyi** [comment]
@francislagares I can't reproduce it with my OpenAPI config, could you share GraphQL schema and url to config file or file itself?

**Comment by francislagares** [comment]
@msadovyi I could now initialize the API but then fails and get error:
 API Pets is declined 😵.
Check you API and data source configs

I'm trying out from this api => https://petstore.swagger.io/v2/swagger.json

This is what I've done within the dashboard:
1. Added that url in Data Connector Configuration.
2. Create /pets endpoint and add Pets datasource.

Do I have to config anything else ? Do I have to create GraphQL schema ?
How do I have to do it ? 
Please if you could show me all the steps I have to follow, 
would be great because I'm not sure if I need to fill in more inputs, and so on.

**Comment by msadovyi** [comment]
@francislagares Thanks! Try to pull our latest image and follow tour steps again. There were a bug related to OpenAPI handler.

**Comment by francislagares** [comment]
Now it's working, awesome !

![pets](https://user-images.githubusercontent.com/43886198/132215467-523f7b96-1506-4293-8929-1f798a5b8ec5.png)

Many thanks, please keep up with this great work !

**Comment by msadovyi** [comment]
Thank you! Ping me here if you have any issues!
