### ISSUE TITLE
Request Headers (Authorization)

### ISSUE THREAD

**Issue by Erislandys** [GraphQL-Portal/graphql-portal#519]
### Discussed in https://github.com/GraphQL-Portal/graphql-portal/discussions/517

<div type='discussions-op-text'>

<sup>Originally posted by **rmolinet** September  4, 2021</sup>
Seems like th Graphql Portal Gateway remove the Authorization request header, the API return UNAUTHENTICATED error everytime, please can anybody help how config the Gateway to allow Authorization header. Thanks.</div>

**Comment by msadovyi** [comment]
Hi, @Erislandys! You have to add the operation/schema header to you source.
Click at "edit data-source" -> "Data Connector Configuration" -> and add Schema/Operation Headers like bellow. 
<img width="1386" alt="Снимок экрана 2021-09-07 в 13 52 23" src="https://user-images.githubusercontent.com/51121816/132332954-a578a85c-32f3-4763-a627-4932c449b853.png">
It will map gateway request header "auth-header" to source request header "authorization". 
You can rename it and use any gateway header you want.
Open gateway playground and send any request with header { "auth-header": "my_dynamic_token"}, source will get request with {"authorization": "Bearer my_dynamic_token"} header.

Thanks!

**Comment by Erislandys** [comment]
@msadovyi  thank you very much, it works,
