### ISSUE TITLE
CORS validation error

### ISSUE THREAD

**Issue by Erislandys** [GraphQL-Portal/graphql-portal#520]
CORS validation error

From a web application I try to authenticate with an API published through the gateway. In the **CORS** configuration I have added the domains and IP of the web application but it keeps showing me an error with the **CORS**

![image](https://user-images.githubusercontent.com/1890370/132885671-845f1962-9ee0-4c2a-86c1-dfc3b6ef78da.png)

Gateway.yaml

hostname: "0.0.0.0"
listen_port: 3000
pool_size: 1
servername: "DOMAIN"
redis:
  connection_string: "@@REDIS_CONNECTION_STRING"
use_dashboard_configs: true
enable_metrics_recording: true
dashboard_config:
  connection_string: "@@DASHBOARD_CONNECTION_STRING"
  secret: ""
cors:
  enabled: true
  origins: (I have tried different ways )
    - IP
    - IP:PORT
    - http://IP:PORT
    - DOMAIN
    - *.DOMAIN
    - http://DOMAIN
  allowedHeaders:
    - Content-Type
    - X-Amz-Date
    - X-Amz-Security-Token
    - Authorization
    - X-Api-Key
    - X-Requested-With
    - Accept
    - Access-Control-Allow-Methods
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
enable_control_api: false
log_level: "info"

**Comment by msadovyi** [comment]
Hi, @Erislandys! You have to add the origins of the graphql-portal-dashboard backend and frontend. For example, if you are running dashboard on "http://somedomain.com" using default ports your gateway.yaml looks like this:
```
dashboard_config:
  connection_string: "http://somedomain.com:3030"
cors:
  enabled: true
  origins:
    - http://somedomain.com:8080
    - http://somedomain.com:3030
```

Also you can check what origins header you have send to gateway and double-check what origins you have added to CORS options in the gateway logs.

**Comment by Erislandys** [comment]
thanks @msadovyi, I have also had to add the domain of the client application to be able to consume the API connecting to the gateway.

The problem is that all the applications are within the same domain (app, gateway and API), you should not have problems with CORS

Solved!!
